### ISSUE TITLE
Add circuit breaker support

### ISSUE THREAD

**Issue by pettermahlen** [spotify/apollo#118]
See for instance http://martinfowler.com/bliki/CircuitBreaker.html. 

The main benefits we're looking for here:
1. In the case of a slow dependency, we've already got TTLs that help set a maximum latency added to requests (that will be roughly the TTL), but essentially all requests will hit that maximum latency. With a circuit breaker that treats timeouts as failures, we can get reduced latency while it is tripped.
2. Allowing failing services breathing room to recover.

**Comment by lepistone** [comment]
Closing because of staleness.
