### ISSUE TITLE
How to configure the ListeningExecutorService

### ISSUE THREAD

**Issue by scribahti** [spotify/apollo#134]
https://github.com/spotify/apollo/tree/master/apollo-core#scoped-executors

Is it possible to configure the number of threads used to initialize the ListeningExecutorService that is exposed by the Service.Instance object?

**Comment by pettermahlen** [comment]
It is not possible to configure - see https://github.com/spotify/apollo/blob/1.x/apollo-core/src/main/java/com/spotify/apollo/core/ServiceImpl.java#L256 for how it gets created.

Also, please note that in the upcoming 2.0 release, the instance-managed executors are going away (see #109), so making that configurable is not likely to get prioritised.

**Comment by scribahti** [comment]
Thanks for the info, Petter!

**Comment by pettermahlen** [comment]
Closing this as the question seems answered - feel free to reopen if needed.
