### ISSUE TITLE
Confusing ClientId comparator for simple use cases

### ISSUE THREAD

**Issue by rouzwawi** [spotify/apollo#136]
I'm creating an Apollo `Service` for using the client only. It looks like this:

``` java
    final Service cliService = Services.usingName("styx-cli")
        .withEnvVarPrefix(ENV_VAR_PREFIX)
        .withModule(ApolloEnvironmentModule.create((a,b) -> 0)) // <-- this
        .withModule(HttpClientModule.create())
        .build();
```

I only have one explicit client module mixed in, but I'm still forced to supply a comparator for client implementations. It would be convenient to have a constructor like `ApolloEnvironmentModule.createDefault()` that would not specify any particular order order for the client.

Relates to #64

**Comment by klaraward** [comment]
Closing issue as project has been moved to be Spotify internal
