### ISSUE TITLE
Simplify external testing by providing a Client that can send HTTP requests

### ISSUE THREAD

**Issue by pettermahlen** [spotify/apollo#141]
Currently, if you want to do an integration test of a running, complete service (i.e., not via the ServiceHelper, which doesn't open any sockets), you need to send raw HTTP messages via your own HTTP client and interpret the results manually. It would probably be cleaner to write test code if there was a way to do something along the lines of

```
import com.spotify.apollo.Client;

class MyIntegrationTest {
  // - some things omitted

  Client client;

  @Before
  public void setup() {
     client = Clients.open(HostAndPort.of("localhost", servicePort));
  }

  @Test
  public void shouldBlah() {
    CompletionStage<Response<ByteString>> responseStage = client.send(Request.forUri("/floop"));
   // ... do something with the response
  }
```

**Comment by DixitPatel** [comment]
Hey @pettermahlen I was wondering if there is any update regarding this issue. I think I can help writing tests like these. Let me know! Thanks!

**Comment by klaraward** [comment]
Closing issue as project has been moved to be Spotify internal
