### ISSUE TITLE
Interface classes in apollo-api-impl

### ISSUE THREAD

**Issue by pettermahlen** [spotify/apollo#146]
There are some interface/abstract classes in apollo-api-impl that are very useful for hooking into Apollo, for instance: 
- `EndpointRunnableFactory`
- `ForwardingOngoingRequest`
- `OngoingRequest`
- `RequestRunnableFactory`

There are probably more. This means that other modules, like apollo-meta, etc., have a dependency on an internal implementation module. It seems like these should be separated out into their own artifact. Probably, it would be good to keep apollo-api as the API definitions for application developers, and add a new set of API definitions for assembly/platform developers?

**Comment by pettermahlen** [comment]
@rouzwawi WDYT?

**Comment by klaraward** [comment]
Closing issue as project has been moved to be Spotify internal
