### ISSUE TITLE
add methods to Request to add parameters

### ISSUE THREAD

**Issue by mattnworb** [spotify/apollo#154]
When writing unit/integration tests that use ServiceHelper to test routes, it would be helpful if I could add parameters to a Request object with a method like `request.withParameter("foo", "bar")` similar to existing "with" methods like `withHeader`, `withPayload` etc.

Currently in order to set the request parameters that are sent in a Request I have to add them in the URI like `Request.forUri("http://service/foo?bar=bat")`, but I would prefer to do this programmatically.

**Comment by pettermahlen** [comment]
A reference could be [HttpUrl from OkHttp](https://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/HttpUrl.html). Their choice was to separate the URL into a different type from the `Request`. Seems like introducing a similar type into Apollo might be good?

**Comment by mattnworb** [comment]
@pettermahlen I think that would be useful. I've wished a few times for something similar to a URIBuilder from Jersey or Http Client that was a bit more standard (especially when not using one of those libraries).

**Comment by pettermahlen** [comment]
I'm thinking if the use case is HTTP urls, then perhaps using `HttpUrl` might be a good solution? Reading the HttpUrl (which is based on experiences from URL, URI and URIBuilder) javadocs, it's striking that creating such a class is a pretty significant effort. Duplicating that in Apollo seems a little wasteful if not strictly necessary.

**Comment by mattnworb** [comment]
I agree on avoiding duplication (or second efforts to create standards-correct URI builders). HttpUrl sounds good to me since it looks very standalone from the rest of okhttp 👍

**Comment by pettermahlen** [comment]
So can we close this and recommend the use of this pattern:

```
  HttpUrl httpUrl = ... ;
  Request.forUri(httpUrl.toString());
```

It's maybe a bit dangerous given that the behaviour of toString() isn't defined in the javadocs. Also, that leaves us without a solution for Hermes URLs, but that's maybe less of a problem as query parameters aren't very commonly used with Hermes.

**Comment by mattnworb** [comment]
Sounds good!
