### ISSUE TITLE
Is there support for CORS? If not, are there plans to add it? If not, can I submit a PR?

### ISSUE THREAD

**Issue by davidxia** [spotify/apollo#210]
Is there support for CORS? If not, are there plans to add it? If not, can I submit a PR?

Ideally there would be out-of-the-box CORS support. Adding something like this to the `.conf` file perhaps.

```
http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length
```

Spotify people who work with our internal version of apollo will know more about what I'm getting at.

**Comment by davidxia** [comment]
cc @martina @pettermahlen @rouzwawi

**Comment by martina-if** [comment]
@davidxia We don't have any plans to add it. You can use it in the internal version. I don't know why it is not part of the open source version. If you want, please submit a PR :)
