### ISSUE TITLE
How to get remote client IP for a request?

### ISSUE THREAD

**Issue by davidxia** [spotify/apollo#216]
I want to get from a `RequestContext` (or perhaps some other class) the client's IP address. How can I do that? `RequestMetadata` from `RequestContext` always seems to have an `Optional.empty` for `HostAndPort`. https://github.com/spotify/apollo/blob/master/apollo-api-impl/src/main/java/com/spotify/apollo/request/OngoingRequest.java#L96

**Comment by davidxia** [comment]
cc @pettermahlen

**Comment by pettermahlen** [comment]
I don't recall exactly how it works any more, but whether the `RequestMetadata` has a valid `HostAndPort` or not is dependent on the server implementation. If it's capable of finding that information, it should be there. Not all server implementations support that, IIRC, and there may be conditions when a server is unable to set it. But in principle, `RequestMetadata` is the place to find the remote IP, and then it depends on your server (Hermes, HTTP/something) if the data is there or not.

**Comment by martina-if** [comment]
Hi David, I was also looking into this and it was a bit confusing. Maybe this PR helps answering your question: https://github.com/spotify/apollo/pull/194
That's when we added logging for the host and port. You might also want to check the internal apollo.

**Comment by klaraward** [comment]
Closing issue as project has been moved to be Spotify internal
