### ISSUE TITLE
Change master branch back to 1.x branch?

### ISSUE THREAD

**Issue by mattnworb** [spotify/apollo#223]
The `master` branch currently has the unreleased 2.0 version of Apollo which doesn't seem to have any active plans for release or further development.

When people make pull requests to change behavior in 1.x, they tend to instinctively do this against `master`, not realizing the state that it is in. They then need to go back and apply their change to the `1.x` branch as well (see #221 #220 #217 etc).

Since the 2.0 version doesn't have plans for a release or finishing any time soon, would it be possible to flip the branches around so that there is a `2.0` branch for the 2.0 refactoring and `master` reflects the 1.x versions being released?

**Comment by pettermahlen** [comment]
This seems like a good idea to me - or if not this, then wrapping up the work left on getting 2.0 out so as to not have this situation with two branches needing to be kept in sync. The belief when branching out was that this state would last for a small number of months.

**Comment by mattnworb** [comment]
@gimaker

**Comment by gimaker** [comment]
@mattnworb Yes, I agree.

**Comment by mattnworb** [comment]
Any ideas on how to move forward on this? Should we simply swap the branches around?

Btw I think you can make the default branch in github be something other than “master”, which might also reduce confusion.

**Comment by lepistone** [comment]
The default branch is indeed set to `1.x`. At this point this is probably the least amount of confusion. Feel free to re-open, thanks!
