### ISSUE TITLE
Requests with "Transfer-Encoding: chunked" wrongly conclude that no payload is being sent

### ISSUE THREAD

**Issue by excentris** [spotify/apollo#243]
When sending a request with the header [Transfer-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding): chunked, Apollo is concluding that no payload is being sent due to the fact that getting the content length of such request may return -1 (unknown length). Such header indicates that the payload is being sent as a series of chunks.

I think that Apollo should still try to read the streamed payload in such a case before concluding that it is empty. I am wrapping up a fix for this which I expect to submit later today.

**Comment by gimaker** [comment]
Fixed by #244
