### ISSUE TITLE
Server Side Event for server-side push

### ISSUE THREAD

**Issue by gianluca-valentini** [spotify/apollo#250]
Hi,
I'd like to understand and imlement SSE using Apollo. 
What I should do to create a notification service that return a message to the client if something change on server side?
It is just like a Route.async operation?

**Comment by gianluca-valentini** [comment]
Looking 

https://github.com/spotify/apollo/issues/82

I understand that Apollo does not support WebSocket but suggest to use SSE. 
How I can use SSE with Apollo with IExplorer too? 
Looking https://caniuse.com/#feat=eventsource neither IE neither EDGE support it.

Can somebody can help me?

**Comment by caesar-ralf** [comment]
Hey, we are closing this issue as we didn't manage to address it and we archiving the project. If you are in spotify org, you can raise in the internal Apollo channels.
