### ISSUE TITLE
Route execution elapsed time

### ISSUE THREAD

**Issue by gianluca-valentini** [spotify/apollo#258]
Hi, 
I'm using Apollo 1.6.5. Is there a way to know the routes elapsed time?

I'd like to know if there is something that can tell me, for each called route,  the execution time.
Is possible for example using some Middleware?
Thanks
Gianluca

**Comment by caesar-ralf** [comment]
Hey, we are closing this issue as we didn't manage to address it and we archiving the project. If you are in spotify org, you can raise in the internal Apollo channels.
