### ISSUE TITLE
Connect to DB

### ISSUE THREAD

**Issue by davidegiannella** [spotify/apollo#281]
Hello, I'm POCing with apollo to see the feasibility and so far so good. Pretty straightforward despite the lack of docs ;).

Now I'd like to connect my app to a Database (postgres for now). I'm not sure what best, recommended way is.

By browsing the codebase I was tempted in implementing a Module (`AbstractApolloModule`) like the Slack one which will provide the connection pool I could later on use in the app to deal with the DB.

What about apollo-entity?

Thank you

**Comment by klaraward** [comment]
Hi,
there is very little active development of Apollo done by Spotify. 
We think you will have better support if you choose another framework.

Best of luck :)
