### ISSUE TITLE
Upgrade to Guice 5

### ISSUE THREAD

**Issue by backuitist** [spotify/apollo#350]
Guice 5.0.1 is out! https://github.com/google/guice/wiki/Guice501

We're hoping to get rid of the spurious warnings: https://github.com/spotify/apollo/issues/246

**Comment by caesar-ralf** [comment]
Hej! Good suggestion @backuitist. We're currently working the nitty-gritties to make this possible

**Comment by caesar-ralf** [comment]
We didn't find any major breaking change with the move we will be slowly moving projects to it. If you want to try out a release candidate version `1.19.0-RC` has been published @backuitist
