### ISSUE TITLE
What about security?

### ISSUE THREAD

**Issue by DinisCruz** [spotify/apollo#54]
Namely, Authentication and Authorisation?

**Comment by pettermahlen** [comment]
There's no built-in support for that in Apollo, if that's what you're asking? A nice way to solve it is via a ```Middleware``` that you wrap your protected endpoint handlers in. It's definitely something that could be a useful additional library for Apollo, but it's not at the moment something we have use for internally, so I doubt that we'll be building it ourselves anytime soon.

**Comment by pettermahlen** [comment]
Closing this as there's not been any feedback on what requirements you actually have in mind - feel free to reopen if you can find the time to clarify.
