### ISSUE TITLE
Clarify requirements on and behaviour of MetaModule

### ISSUE THREAD

**Issue by pettermahlen** [spotify/apollo#63]
Some things that are currently more or less broken:

- #13 
- ```MetaModule``` specifies a 'container version' which is hard-coded to 'apollo-standalone' + the apollo version. The latter is retrieved from a file named 'metaDescriptor.properties' on the class path.
- The 'meta' API is exposed on the same port as the main service, under a 'path tree' starting with '_meta'. 
- The APIs are defined in apollo-api-impl, which is not 'public', making it unclear if we're breaking backwards compatibility by changing something like MetaGatherer.

**Comment by pettermahlen** [comment]
Maybe one thing to consider is extracting 'meta' stuff into its own module. I'm not sure it's necessary or helpful to include it in environment.

**Comment by rouzwawi** [comment]
As mentioned in #64, I think we should look at inverting the dependency between `MetaModule` and `EnvironmentModule`. 

Has some benefits:

* Lets us have a cleaner definition of what metadata we expose from an application
* Makes it easier and cleaner to bind the meta api to a separate server or even other protocols

**Comment by pettermahlen** [comment]
Adding this to the 2.0.0 milestone; we should consider whether we want to include it there or not.
