### ISSUE TITLE
Examples fail to start with -Dhttp.server.port=8080

### ISSUE THREAD

**Issue by andrestc** [spotify/apollo#69]
Starting up on windows 10, with the following command (stated in the docs):
```java -jar target/java-exam.jar -Dhttp.server.port=8080```

Gives the following warning:
```16:59:16.373 [main] WARN  c.s.a.http.server.HttpServerProvider - Not loading http server - enable with: http.server.port = 8080```

Running just: ```java -jar target/java-exam.jar``` works (I have the port configured on the .conf file).

Maybe this is not actually a bug, but the docs should be updated then.

Thanks.

**Comment by dkowis** [comment]
I'm having the opposite problem. I can't get it to start the HTTP server unless I pass in `-Dhttp.server.port=8080`.

**Comment by rouzwawi** [comment]
@andrestc Can you check what the first line of log output you get is? You might have to configure some logging library to see the log output. I've updated the example to be a bit more thorough in how to set up the maven build in #70 .

My hypothesis is that it has something to do with command line argument handling in Windows (I'm not a windows user though, so just a guess). My output looks like this:

```
$ java -jar target/ping.jar -Dhttp.server.port=9999
22:20:01.934 [main] DEBUG c.s.apollo.httpservice.HttpService - Trying to create instance of service ping with args [-Dhttp.server.port=9999]
...
```

**Comment by rouzwawi** [comment]
@dkowis Is the config file in `src/main/resources/<service-name>.conf`?

**Comment by dkowis** [comment]
@rouzwawi that was actually my problem. I didn't have it named the same! I'm good to go now :)

**Comment by andrestc** [comment]
My bad, apparently in Windows we need to quote it. This works:
```java -jar target/java-exam.jar "-Dhttp.server.port=8080"```
