### ISSUE TITLE
Request#header(String) should be case insensitive for HTTP requests

### ISSUE THREAD

**Issue by udoprog** [spotify/apollo#71]
See http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html
From 4.2 Message Headers: "Field names are case-insensitive."

This will otherwise cause problems when interacting with proxies or clients that perform pre-emptive all-to-lowercase/uppercase [example here](https://github.com/nodejs/node-v0.x-archive/issues/1954) before the request hits the Apollo-based service.

**Comment by pettermahlen** [comment]
What exactly is the problem in the Apollo code base?

**Comment by udoprog** [comment]
[Request#header(String)](https://github.com/spotify/apollo/blob/master/apollo-api/src/main/java/com/spotify/apollo/Request.java#L77) is not case-insensitive, which should probably happen in [ApolloRequestHandler in the jetty-http-server module](https://github.com/spotify/apollo/blob/master/modules/jetty-http-server/src/main/java/com/spotify/apollo/http/server/ApolloRequestHandler.java#L90)

**Comment by pettermahlen** [comment]
Right, of course, it was in the title. We should define whether ```Request``` itself considers headers to be case-sensitive or not, I think. I don't have any strong opinions about that, but I think I would like to make it case-insensitive like for HTTP.

**Comment by pettermahlen** [comment]
Addressed in #93

**Comment by pettermahlen** [comment]
Fixed via #96
