### ISSUE TITLE
Unit Tests for improved test coverage

### ISSUE THREAD

**Issue by furknyavuz** [spotify/apollo#72]
Hi Spotfy team!

I'm currently working at devfactory. We are looking for open source projects to make them more reliable. Will it be helpful if we write some unit tests for certain modules to improve overall tested code coverage?

I'm looking forward to hearing from you.
Kind regards,

**Comment by pettermahlen** [comment]
We welcome any improvements, be that unit tests or production code changes. To be clear, we don't consider improved code coverage to be a good thing for its own sake - rather that it's a proxy metric for unit test quality. So we'll be more likely to accept PRs with good unit tests that validate features that aren't currently well tested than PRs that just exercise some lines of code that were previously untested.

Looking forward to seeing what you can come up with - and if you spot other things than unit tests that can be improved, don't hesitate to submit other kinds or PRs!
