### ISSUE TITLE
Expose ExecutorService's ThreadPoolExecutor for metrics collection

### ISSUE THREAD

**Issue by andredasilvapinto** [spotify/apollo#80]
Or an abstraction that enables access to the thread pool usage metrics like number of active threads, current pool size, max pool size, task count...

Right now there is no way to obtain those values afaik:
https://github.com/spotify/apollo/blob/master/apollo-core/src/main/java/com/spotify/apollo/core/ServiceImpl.java#L259

**Comment by rouzwawi** [comment]
These can be accessed through [`Service.Instance.get(Scheduled)ExecutorService()`](https://github.com/spotify/apollo/blob/master/apollo-core/src/main/java/com/spotify/apollo/core/Service.java#L199-L218). However, they are not exposed through ['apollo-environment'](https://github.com/spotify/apollo/tree/master/apollo-environment) to a regular apollo service application.

You would not be able to use these executors from a regular application. So getting metrics for them there would be moot?

Can you describe where you're using these?

**Comment by andredasilvapinto** [comment]
I'm not asking for access to the ListeningExecutorService, that doesn't provide the necessary methods for metrics collection. I'm asking for the ThreadPoolExecutor, used by the ExecutorService, so I can get access to methods like this: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#getActiveCount%28%29

I can submit tasks to the ExecutorService from a regular application, so it's useful to know the state of that thread pool.

It's an internal project, I will send you a link to the code through slack.

**Comment by pettermahlen** [comment]
This is no longer relevant (for 2.x) since there are no longer shared thread pools provided by Apollo.
