### ISSUE TITLE
Add support for WebSockets

### ISSUE THREAD

**Issue by lndbrg** [spotify/apollo#82]
We are soon going to build systems that have a need for real time updates from the servers. Exposing nettys built in support for WebSockets in our routing engine would help us tremendously with that task.

**Comment by perfa** [comment]
Firmly seconded :+1:

**Comment by pettermahlen** [comment]
Do you have any more concrete ideas how you would like to use websockets from your backend code? What would you like your code to look like?

**Comment by lndbrg** [comment]
So this is what I come up with on the spot. Probably needs some rework in the end. But it's a starting point

```java
    public Stream<Route<AsyncHandler<Response<ByteString>>>> routes() {
      Stream<Route<? extends AsyncHandler<?>>> routes = Stream.of(
            Route.sync("POST", "/give-me-a-payload", this::mundaneHTTP),
            // If you want to handle connect/disconnect yourself:
            Route.webSocket(WebSocket.CONNECTED, '/streams-tastes-amazing', this::webSocketConnected)),
            Route.webSocket(WebSocket.DISCONNECTED, '/streams-tastes-amazing', this::webSocketDisconnected)),
            Route.webSocket(WebSocket.MESSAGE, '/streams-tastes-amazing', this::webSocketMessage)),
            //If you want to let apollo handle connect/disconnect. e.g keeping track of the current sessions:
            Route.webSocket(WebSocket.MESSAGE, '/streams-tastes-amazing', this::webSocketMessage))
                    .withLifeCycle() //should give you a separate session storage for each route.
            )

        return routes.map(r -> r.withMiddleware(Middlewares.apolloDefaults()));
    }
```
Let apollo handle the sending of data back to the client if we do simple things:
```java
    public String webSocketMessage(String message) throws IOException {
        System.out.println("Got: " + message);   // Print message
        return message;
    }

     //This should ideally do the same wrapping as apollo does but in the end call:
     session.getRemote().sendString(instance.webSocketMessage(message));
```

for more complicate things, expose the session so we can decide how to send
```java
    public void webSocketMessage(Session session, String message) throws IOException {
        System.out.println("Got: " + message);   // Print message
        session.getRemote().sendString(message); // and send it back
    }
```

There also needs to be away to get all the connected sessions for a route (as a list or stream), maybe something like this? *Unless you manage the lifecycle yourself with connect/disconnect*
```java
    environment.getWebsocketSessions().ofRoute('/streams-tastes-amazing').forEach(this::broadcastMessage);

    public void broadcastMessage(Session session) {
       session.sendString("Spam, spam, spam");
    }

**Comment by lndbrg** [comment]
the thing that stores the sessions in apollo with the default lifecycle might look something like this:

```java
    private static final Queue<Session> sessions = new ConcurrentLinkedQueue<>();

    public void connected(Session session) {
        sessions.add(session);
    }
    public void closed(Session session, int statusCode, String reason) {
        sessions.remove(session);
    }
```

netty also exposes:
`@OnWebSocketError`
and
`@OnWebSocketError`
http://www.eclipse.org/jetty/documentation/current/jetty-websocket-api-annotations.html

**Comment by javoire** [comment]
+1 on this feature

**Comment by mattnworb** [comment]
Is it common for a service that has websocket endpoints to also have multiple regular http endpoints? I am curious if the API needed for websockets is so different than the 1:1 request:response mapping that Apollo supports today that a more specialized library/API (devoted to websocket services) would make more sense.

**Comment by pettermahlen** [comment]
So far, I've been thinking about this (vaguely and without really understanding much) in terms of something like [reactive streams](http://www.reactive-streams.org/). So the thing that processes websocket messages would be a Subscriber to incoming messages, and a Publisher of outgoing messages. RxJava Observables as inputs and outputs might be a nice option as well.

I've also been thinking about it as a separate kind of server - so not a regular Apollo HTTP server, but something else. Things that Apollo has that seem to be useful to preserve include:
- route management
- configuration support
- logging
- statistics (when we make that open source, in particular)
- etc. 

I agree it's quite likely to be something else than a normal Apollo HttpServer. It feels like it would be simpler to not support web sockets and regular HTTP calls on the same port, and if so, that would mean that it would be simpler to not support regular HTTP and web sockets in the same Apollo application out of the box.

Is that more or less what you mean when you say 'a more specialised library'?

**Comment by mattnworb** [comment]
> Is that more or less what you mean when you say 'a more specialised library'?

Yep!

**Comment by jocelinzl** [comment]
+1 on this feature

**Comment by eshwaran** [comment]
:+1: Want this too!

**Comment by pettermahlen** [comment]
Background info: https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/preview

**Comment by pettermahlen** [comment]
Link to RFC/design document: https://docs.google.com/document/d/10hKrJDH8NubEAkONI1IIJCs2wzi5am-SNp3z7bldL-w/edit#

**Comment by fabiopedrosa** [comment]
Any updates on websocket support in Apollo?

**Comment by pettermahlen** [comment]
Yes, we've decided not to do it for now. Apollo's core use case isn't to support full website backend development, it's aimed at backend microservices. So internally at Spotify, we recommend using SSE for server-side push, which is what people most wanted to use websockets for.
