### ISSUE TITLE
Incorrect documentation of RequestContext#pathArgs

### ISSUE THREAD

**Issue by odsod** [spotify/apollo#88]
https://github.com/spotify/apollo/blob/814aaf7aa5bfa2a46817493cec187161f191da29/apollo-api/src/main/java/com/spotify/apollo/RequestContext.java#L49

~~~java
Route.sync("GET", "/test/<thing>",
           rc -> Response.forPayload(ByteString.encodeUtf8(rc.pathArgs().get("thing")))),
~~~

~~~java
  @Test
  public void test() throws Exception {
    final Response<ByteString> response = service.request(Request.forUri(
        "http://localhost:8080/test/the%32rainbow"))
        .toCompletableFuture().get();

    final String expectedPayload = "the%32rainbow";

    assertEquals(expectedPayload, response.payload().get().utf8());
  }
~~~

Expected: `the%32rainbow`
Actual: `the2rainbow`

**Comment by rouzwawi** [comment]
The documentation example uses a path-typed argument in that position. Those are actually returned in their raw form. Your test only specifies `<thing>` which is a regular segment argument which is decoded.

**Comment by odsod** [comment]
Oh! Thanks for clarifying.
