### ISSUE TITLE
Change coverage reporting to codecov.io

### ISSUE THREAD

**Issue by rouzwawi** [spotify/apollo#90]
Opening this up for discussion. I recently tried out https://codecov.io/ on a project and was impressed by their feedback. Some benefits I see over the coveralls integration

* Metrics posted as a comment in the PR, with +/- on coverage
* Their awesome [browser extension][1] which annotate the PR diff view with coverage/missed per line

[1]: https://github.com/codecov/browser-extension#codecov-extension

**Comment by mattnworb** [comment]
We have been using codecov on Helios/docker related repositories and really like it 👍🏻

**Comment by pettermahlen** [comment]
Go for it, I think
