### ISSUE TITLE
Service.Instance Scoped executors has no thread pool size limit

### ISSUE THREAD

**Issue by zalenski** [spotify/apollo#95]
`instance.getExecutorService()` uses `Executors.newCachedThreadPool` which has no thread pool size limit

see http://stackoverflow.com/questions/1800317/impossible-to-make-a-cached-thread-pool-with-a-size-limit

**Comment by zalenski** [comment]
Maybe it could just be removed, it's not used much.

**Comment by pettermahlen** [comment]
I would actually be in favour of removing this for 2.0 - I don't see that providing shared executor services is a good fit for the core of Apollo. It's something that can easily be done at the application level. @rouzwawi ?

**Comment by mattnworb** [comment]
+1 for removal
